//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v4.2.1.3
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace AirTagTracker
{
   public partial class UploadSession
   {
      partial void Init();

      /// <summary>
      /// Default constructor. Protected due to required properties, but present because EF needs it.
      /// </summary>
      protected UploadSession()
      {
         AirTagDatas = new System.Collections.Generic.HashSet<global::AirTagTracker.AirTagData>();

         Init();
      }

      /// <summary>
      /// Replaces default constructor, since it's protected. Caller assumes responsibility for setting all required values before saving.
      /// </summary>
      public static UploadSession CreateUploadSessionUnsafe()
      {
         return new UploadSession();
      }

      /// <summary>
      /// Public constructor with required data
      /// </summary>
      /// <param name="datetimedataaccessed"></param>
      /// <param name="sessiondatetime"></param>
      /// <param name="datetimedatalastmodified"></param>
      public UploadSession(DateTime datetimedataaccessed, DateTime sessiondatetime, DateTime datetimedatalastmodified) : this()
      {
         this.DateTimeDataAccessed = datetimedataaccessed;

         this.SessionDateTime = sessiondatetime;

         this.DateTimeDataLastModified = datetimedatalastmodified;

      }

      /// <summary>
      /// Static create function (for use in LINQ queries, etc.)
      /// </summary>
      /// <param name="datetimedataaccessed"></param>
      /// <param name="sessiondatetime"></param>
      /// <param name="datetimedatalastmodified"></param>
      public static UploadSession Create(DateTime datetimedataaccessed, DateTime sessiondatetime, DateTime datetimedatalastmodified)
      {
         return new UploadSession(datetimedataaccessed, sessiondatetime, datetimedatalastmodified);
      }

      /*************************************************************************
       * Properties
       *************************************************************************/

      /// <summary>
      /// Required
      /// </summary>
      [Required]
      public DateTime DateTimeDataAccessed { get; set; }

      /// <summary>
      /// Required
      /// </summary>
      [Required]
      public DateTime DateTimeDataLastModified { get; set; }

      /// <summary>
      /// Identity, Indexed, Required
      /// Unique identifier
      /// </summary>
      [Key]
      [Required]
      [System.ComponentModel.Description("Unique identifier")]
      public long Id { get; set; }

      /// <summary>
      /// Required
      /// </summary>
      [Required]
      public DateTime SessionDateTime { get; set; }

      /*************************************************************************
       * Navigation properties
       *************************************************************************/

      public virtual ICollection<global::AirTagTracker.AirTagData> AirTagDatas { get; private set; }

   }
}

